### ISSUE TITLE
Weave networking is broken

### ISSUE THREAD

**Issue by gfieni** [Spirals-Team/docker-g5k#8]
Currently, Weave networking support is broken due to changes in the way the plugin is started. ([related PR](https://github.com/weaveworks/weave/pull/2727/files#diff-ed6579eaedd0e67b3ed51c7ee7071044))
Weave provisionning part needs to be accordingly updated.

**Comment by rouvoy** [comment]
As a workaround, can't you use a given (old) version of Weave to keep it working while looking for a more sustainable solution?

**Comment by gfieni** [comment]
Yes it is possible, but the problem is already fixed with the latest version.
I'm adding more tests to avoid silent errors about provisioning in the future.
